### ISSUE TITLE
reorder-list item reordering doesn't work on mobile

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_components#170] opened 2017-10-08 11:12 UTC
E.g., try https://angulardart-org-dev3.firebaseapp.com/examples/web-angular (which is using version 0.7.1).

cc @kwalrath

**Comment by nshahan** [comment] 2017-10-09 18:04
Duplicate of #19.

**Closed by nshahan** 2017-10-09 18:04 UTC

**Comment by chalin** [comment] 2017-10-11 20:29
Well, not quite a duplicate of #19, given that it doesn't work under iOS either.

**Comment by chalin** [comment] 2017-10-11 20:30
Maybe #19 needs to be slightly generalized?
