### ISSUE TITLE
Example : Reorder list fails in Safari

### ISSUE THREAD

**Issue by sandrobilbeisi** [dart-lang/angular_components#98] opened 2017-05-25 11:11 UTC
Hello

symptom: reorder list doesn't work in Safari
angular_components 0.5.2

the Example : reorder list https://dart-lang.github.io/angular_components_example/#ReorderList
fails in Safari 10.1.1 (10603.2.5), Mac OS X Yosemite 10.10.5
I've tried disabling Safari Extensions and have run the system in Safe mode
but the error remains consistent ...

p.s. it works just fine on:
 - Chrome 58.0.3029.110 (64-bit), Mac OS X Yosemite 10.10.5
 - FireFox 53.0.3 (64-bit), Mac OS X Yosemite 10.10.5
 - Opera 42.0.2393.137, Mac OS X Yosemite 10.10.5

**Comment by nshahan** [comment] 2017-05-25 16:04
Thanks for pointing it out. I can confirm I am seeing the same problem.

**Comment by nshahan** [comment] 2017-05-25 17:50
Looks like it is related to a change in the mouse vs drag events in the SDK.  dart-lang/sdk@fbbb974 
 Reorder Lists work in safari when you build with the stable version of the SDK (1.23). We are investigating a fix.

**Comment by nshahan** [comment] 2017-08-17 23:16
The issue does not appear in the latest version of webkit nightly. Hopefully the update will be included in the next stable release.

**Closed by nshahan** 2017-08-17 23:16 UTC
Labels: Type: bug
