### ISSUE TITLE
Support autocomplete attribute on material-input

### ISSUE THREAD

**Issue by grundid** [dart-lang/angular_components#345] opened 2018-10-17 14:42 UTC
It would be nice to have the autocomplete attribute on input fields to be able to use Autofill.

https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#use_metadata_to_enable_auto-complete

**Comment by nshahan** [comment] 2018-10-17 19:56
Duplicate of #261.

**Closed by nshahan** 2018-10-17 19:56 UTC
