### ISSUE TITLE
selectedTime is not reset in MaterialTimePickerComponent when new time is set

### ISSUE THREAD

**Issue by grundid** [dart-lang/angular_components#274] opened 2018-06-15 10:56 UTC
When the component is reused the selectedTime variable is not cleared and the user is not able to select the same time again. You have to deselect and select the time again.

**Comment by nshahan** [comment] 2018-06-15 23:00
cc @cpelling Any thoughts about this?

**Comment by yuandong** [comment] 2018-07-20 14:30
Hi Adrian, 
just want to make sure I get the step to reproduce it:
1. Select time in the dropdown, 5:00 AM for instance.
2. You set the new time in input box directly, 6:30 AM for instance.
3. You try to select 5:00 AM from the dropdown again and you are bot able to do it because the dropdown already selected 5:00 AM.

The expected behavior will be whenever you set a new time from input box, selectedTime need to be cleared out so that you can select any time from the dropdown. (One edge case will be if we only set hour in input box, we may disable corresponding item in the dropdown)

**Comment by grundid** [comment] 2018-07-30 09:15
Sure. The problem is that selectedTime is not reset when the time is set programmatically. 

The steps to reproduce are:
- user selects a time in the select list
- some other event makes the business logic change the time to a new value
- now user wants to select the same time as before. 

This is now not possible because the select list still shows the old time and no change event is generated when the user tries to select the new time.

**Comment by yuandong** [comment] 2018-08-02 18:54
Aha, get it. It's fixed now. Will be included in the next release.

**Closed** 2018-08-04 21:32 UTC

**Comment by grundid** [comment] 2018-12-28 14:13
I noticed a regression with this fix and would like to suggest a different solution. With the current solution `selectedTime.clear()` the selected time is reset correctly but the position in the drop down is lost. Also the programmatically selected value is not selected in the drop down list at all.

Please change `selectedTime.clear()` to `selectedTime.select(value)`
If the value does not exists in the select list it won't be selected, so the value is reset.

**Comment by yuandong** [comment] 2019-01-08 13:33
Right, already added it to the fix, test case covered it.
